name: Consumer Bump
description: Version bump steps specific to this repo

inputs:
  github-token:
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Create version packages pull request
      uses: changesets/action@v1
      with:
        version: npm run version
        title: "chore: version packages"
        commit: "chore: version packages"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
