name: Release Automation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    uses: dielduarte/shared-workflows/.github/workflows/js/release-automation.yml@main
    permissions:
      id-token: write
      contents: read
    secrets: inherit
